# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03ca8d31ccee827d37530df9963fd9c894218c80a922384927e62c7336e39ed178c49838412336932b1b2b0f63d0f93c06411236bb80d3e16304c48356495ae2

test:
  secret_key_base: b55d9c7fddd598cab034edb2b5fedcbb5557d74b4ed64ef1508688fa0aa03fe7e8d58507f41b1e292547b76449819edf29cfde3f6ff74911de97d2ddfa5612bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
